const assert = require('node:assert/strict');
const fs = require('node:fs');
const net = require('node:net');
const path = require('node:path');
const { spawn, spawnSync } = require('node:child_process');
const { once } = require('node:events');
const { test } = require('node:test');
const { loadBotProject } = require('@monky/bot-sdk/dist/tooling/config');
const { hostConsentFingerprint } = require('@monky/bot-sdk/dist/cli/consent');
const { loadOrCreateBotKeys } = require('@monky/bot-sdk/dist/cli/keys');

const ROOT = path.resolve(__dirname, '..');
const SDK_TOOLS = require.resolve('@monky/bot-sdk/dist/tools.js');
const RUNNER = require.resolve('@monky/bot-sdk/dist/cli/runner.js');
const ENTRY = path.join(ROOT, 'dist', 'index.js');
const project = loadBotProject(ROOT);
const fingerprint = hostConsentFingerprint(project.definition);

function profile(t) {
  const home = fs.mkdtempSync(path.join(__dirname, '.runtime-cli-'));
  const state = { home, dir: path.join(home, '.monkybot'), children: [] };
  // Stop the bot before removing its files: Windows keeps them locked while it runs.
  t.after(async () => {
    for (const { child, exited } of state.children) {
      if (child.exitCode === null && child.signalCode === null) {
        child.kill();
        await exited;
      }
    }
    fs.rmSync(home, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
  });
  return state;
}

function environment(home, extra = {}) {
  const env = {
    ...process.env, HOME: home, USERPROFILE: home, MONKY_BOT_CLI_HOME: home, CI: '1',
    NODE_OPTIONS: '', NODE_PATH: '', LANG: '', LC_ALL: '', LC_MESSAGES: '', LANGUAGE: '',
    ...extra,
  };
  for (const name of ['MONKY_BOT_LOCALE', 'MONKY_LANG', 'MONKY_HOST_CONSENT', 'MONKY_SERVE', 'MONKY_SERVE_PORT',
    'MONKY_SERVE_HOST', 'MONKY_SERVE_PUBLIC_HOST', 'MONKY_SERVER_URL', 'MONKY_BOT_TOKEN', 'MONKY_BOT_PUBLIC_KEY',
    'MONKY_BOT_NAME', 'MONKY_BOT_REGISTRATION_FILE', 'MONKY_GAMES_PORT', 'MONKY_GAMES_HOST', 'MONKY_GAMES_PUBLIC_URL',
    'MONKY_MUSIC_GRACE_SECONDS']) {
    if (!(name in extra)) delete env[name];
  }
  return env;
}

// The same `monky-bot-sdk cli` used by `npm run cli` and the packaged `monkybot` wrapper.
function cli(home, args, { env = {}, status = 0 } = {}) {
  const result = spawnSync(process.execPath, [SDK_TOOLS, 'cli', ...args], {
    cwd: ROOT, env: environment(home, env), encoding: 'utf8', timeout: 30000, windowsHide: true,
  });
  assert.ifError(result.error);
  const output = result.stdout + result.stderr;
  assert.equal(result.status, status, output);
  return output;
}

async function freePort() {
  const server = net.createServer();
  server.listen(0, '127.0.0.1');
  await once(server, 'listening');
  const { port } = server.address();
  await new Promise(resolve => server.close(resolve));
  return port;
}

/** Starts the runner exactly as PM2 and `start --foreground` do, and waits for the manifest. */
async function runConfiguredBot(state, extra = {}) {
  const { home, dir } = state;
  const child = spawn(process.execPath, [RUNNER], {
    cwd: dir, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'],
    env: environment(home, {
      MONKY_BOT_CLI_CONFIG_FILE: path.join(dir, 'config.json'), MONKY_BOT_CLI_ENTRY: ENTRY,
      MONKY_BOT_CLI_PACKAGE_ROOT: ROOT, MONKY_BOT_LOCALE: 'en', ...extra,
    }),
  });
  let output = '';
  child.stdout.on('data', chunk => { output += chunk; });
  child.stderr.on('data', chunk => { output += chunk; });
  state.children.push({ child, exited: once(child, 'exit') });
  const deadline = Date.now() + 20000;
  while (!/Manifest: (http:\/\/\S+)/.test(output)) {
    if (child.exitCode !== null) throw new Error(`The runner exited early.\n${output}`);
    if (Date.now() > deadline) throw new Error(`The runner did not serve its manifest.\n${output}`);
    await new Promise(resolve => setTimeout(resolve, 50));
  }
  return { child, logs: () => output, manifestUrl: /Manifest: (http:\/\/\S+)/.exec(output)[1] };
}

test('package.json declares the shared SDK CLI, its release asset and what the host must provide', () => {
  const pkg = require('../package.json');
  const { definition } = project;
  assert.equal(pkg.bin, undefined, 'The packaged monkybot command is generated by the SDK builder.');
  assert.equal(pkg.scripts.cli, 'monky-bot-sdk cli');
  assert.equal(fs.existsSync(path.join(ROOT, 'src', 'cli.ts')), false);
  assert.equal(fs.existsSync(path.join(ROOT, 'src', 'cli')), false);
  assert.equal(definition.cliName, 'monkybot');
  assert.equal(definition.displayName, 'MonkyBot');
  assert.equal(definition.entry, 'dist/index.js');
  assert.deepEqual(definition.files, ['dist', 'assets']);
  assert.deepEqual(definition.modes, ['manual', 'marketplace']);
  assert.deepEqual(definition.releases, {
    url: 'https://github.com/MonkyOrg/MonkyBot/releases', repository: 'MonkyOrg/MonkyBot',
    assetName: 'monky-bot-{version}.tgz', tokenEnv: 'GH_TOKEN',
  });
  assert.deepEqual(definition.requirements.ports, [{
    id: 'games', description: definition.requirements.ports[0].description, protocol: 'tcp',
    portEnv: 'MONKY_GAMES_PORT', defaultPort: 7781, hostEnv: 'MONKY_GAMES_HOST',
    publicUrlEnv: 'MONKY_GAMES_PUBLIC_URL', exposure: 'public', when: 'on-demand', modes: ['manual', 'marketplace'],
  }]);
  assert.deepEqual(definition.requirements.settings.map(setting => [setting.env, setting.required, setting.secret]),
    [['MONKY_MUSIC_GRACE_SECONDS', false, false]]);
  assert.match(definition.requirements.notice['pt-BR'], /YouTube.*computador de quem pede/);
  assert.match(definition.requirements.notice.en, /YouTube.*requester's computer/);
  assert.match(fingerprint, /^[a-f0-9]{12}$/);

  // Each declared variable is one the runtime really reads.
  const sources = ['commands/games.ts', 'music/settings.ts']
    .map(file => fs.readFileSync(path.join(ROOT, 'src', file), 'utf8')).join('\n');
  for (const name of ['MONKY_GAMES_PORT', 'MONKY_GAMES_HOST', 'MONKY_GAMES_PUBLIC_URL', 'MONKY_MUSIC_GRACE_SECONDS']) {
    assert.ok(sources.includes(`process.env.${name}`) || sources.includes(`env.${name}`), name);
  }
});

test('requirements lists the ports to open and the settings in both languages without creating a profile', t => {
  const state = profile(t);
  const { home, dir } = state;
  const english = cli(home, ['requirements', '--locale', 'en-US']);
  assert.match(english, /manifest: TCP 7780 \(allow through the firewall\/router; always\)/);
  assert.match(english, /games: TCP 7781 \(allow through the firewall\/router; on demand\)/);
  assert.match(english, /Set MONKY_GAMES_PUBLIC_URL to the public URL/);
  assert.match(english, /MONKY_MUSIC_GRACE_SECONDS \[optional\]/);
  const portuguese = cli(home, ['requirements', '--locale', 'pt-BR']);
  assert.match(portuguese, /games: TCP 7781 \(liberar no firewall\/roteador; sob demanda\)/);
  assert.match(portuguese, /monkybot doctor/);
  assert.equal(fs.existsSync(dir), false);
});

test('non-interactive setup waits for the host consent fingerprint; the legacy MONKY_HOST_CONSENT=1 no longer counts', async t => {
  const state = profile(t);
  const { home, dir } = state;
  const port = await freePort();
  const setup = cli(home, ['setup', '--non-interactive', '--mode', 'marketplace', '--public-host', '127.0.0.1',
    '--serve-port', String(port), '--locale', 'en-US']);
  assert.ok(setup.includes(`monkybot consent --accept ${fingerprint}`), setup);
  assert.match(setup, /games: TCP 7781/);
  assert.equal(JSON.parse(fs.readFileSync(path.join(dir, 'host-consent.json'), 'utf8')).state, 'pending');

  assert.match(cli(home, ['start', '--foreground', '--locale', 'en-US'], { status: 1 }), /has not been confirmed yet/);
  assert.match(cli(home, ['start', '--foreground', '--locale', 'en-US'], { status: 1, env: { MONKY_HOST_CONSENT: '1' } }),
    new RegExp(`does not match this version's access.*MONKY_HOST_CONSENT=${fingerprint}`));
  assert.equal(fs.existsSync(path.join(dir, '.keys')), false, 'Nothing may run or create an identity before consent.');

  assert.match(cli(home, ['consent', '--accept', 'abcdef123456', '--locale', 'en-US'], { status: 1 }), /fingerprint/i);
  cli(home, ['consent', '--accept', fingerprint, '--locale', 'en-US']);
  const consent = JSON.parse(fs.readFileSync(path.join(dir, 'host-consent.json'), 'utf8'));
  assert.equal(consent.state, 'accepted');
  assert.equal(consent.fingerprint, fingerprint);
  assert.equal(path.resolve(consent.botDir), path.resolve(dir));
});

test('the SDK runner starts the compiled MonkyBot with the profile identity, registrations and saved settings', async t => {
  const state = profile(t);
  const { home, dir } = state;
  const port = await freePort();
  cli(home, ['setup', '--non-interactive', '--mode', 'marketplace', '--public-host', '127.0.0.1',
    '--serve-port', String(port), '--name', 'QA MonkyBot']);
  cli(home, ['consent', '--accept', fingerprint]);
  cli(home, ['config', 'env', 'set', 'MONKY_GAMES_PUBLIC_URL', 'https://games.example.test']);
  cli(home, ['config', 'env', 'set', 'MONKY_MUSIC_GRACE_SECONDS', '90']);
  assert.match(cli(home, ['config', 'env', 'set', 'MONKY_GAMES_PUBLIC_URL', 'https://games.example.test/path', '--locale', 'en-US'],
    { status: 1 }), /without credentials, path/);
  const keys = loadOrCreateBotKeys(dir);

  const run = await runConfiguredBot(state, { MONKY_SERVE_HOST: '127.0.0.1' });
  assert.equal(run.manifestUrl, `http://127.0.0.1:${port}/manifest`);
  const response = await fetch(run.manifestUrl, { signal: AbortSignal.timeout(10000) });
  assert.equal(response.status, 200);
  assert.equal(response.headers.get('x-monky-bot-public-key'), keys.publicKeyHex);
  assert.equal((await response.json()).name, 'QA MonkyBot');
  assert.ok(run.logs().includes(`(${path.join(dir, '.keys', 'registrations.json')})`), run.logs());
  assert.equal(fs.existsSync(path.join(ROOT, '.keys')), false, 'The runtime must not create keys in the checkout.');
  assert.deepEqual(JSON.parse(fs.readFileSync(path.join(dir, 'environment.json'), 'utf8')).values, {
    MONKY_GAMES_PUBLIC_URL: 'https://games.example.test', MONKY_MUSIC_GRACE_SECONDS: '90',
  });
});

test('a profile from the former standalone CLI keeps its identity and language and inherits consent once', async t => {
  const state = profile(t);
  const { home, dir } = state;
  const port = await freePort();
  fs.mkdirSync(dir, { recursive: true });
  const keys = loadOrCreateBotKeys(dir);
  const registrations = path.join(dir, '.keys', 'registrations.json');
  fs.writeFileSync(registrations, JSON.stringify({ version: 1, publicKey: keys.publicKeyHex, registrations: [] }));
  // Written by monkybot <= the last standalone release: no botName, inline hostConsent.
  fs.writeFileSync(path.join(dir, 'config.json'), JSON.stringify({
    mode: 'marketplace', servePort: port, publicHost: '127.0.0.1', botDir: dir,
    hostConsent: { version: 1, botDir: dir },
  }, null, 2));
  fs.writeFileSync(path.join(dir, 'preferences.json'), JSON.stringify({ locale: 'en' }));

  const shown = cli(home, ['config', 'show']);
  assert.match(shown, /marketplace/);
  assert.match(shown, /MonkyBot/);
  assert.match(cli(home, ['consent']), /predates consent/);
  assert.match(cli(home, ['start', '--foreground'], { status: 1, env: { MONKY_HOST_CONSENT: '1' } }),
    new RegExp(`MONKY_HOST_CONSENT=${fingerprint}`));
  assert.equal(fs.existsSync(path.join(dir, 'host-consent.json')), false);

  const run = await runConfiguredBot(state, { MONKY_SERVE_HOST: '127.0.0.1' });
  const response = await fetch(run.manifestUrl, { signal: AbortSignal.timeout(10000) });
  assert.equal(response.headers.get('x-monky-bot-public-key'), keys.publicKeyHex);
  assert.equal(fs.readFileSync(path.join(dir, '.keys', 'public.hex'), 'utf8').trim(), keys.publicKeyHex);
  const consent = JSON.parse(fs.readFileSync(path.join(dir, 'host-consent.json'), 'utf8'));
  assert.equal(consent.state, 'inherited');
  assert.equal(consent.fingerprint, fingerprint);
  assert.match(cli(home, ['consent']), /inherited from an earlier profile/);
});

test('the runtime CLI help is the SDK one, with doctor, requirements and consent', t => {
  const { home } = profile(t);
  const help = cli(home, ['--help', '--locale', 'en-US']);
  for (const command of ['setup', 'doctor [--local]', 'requirements', 'consent [--accept FP|--revoke]', 'config env',
    'update [--check] [--beta] [--yes]', 'autoupdate on [HH:MM] [--beta]']) {
    assert.ok(help.includes(command), command);
  }
  assert.match(help, /^monkybot — MonkyBot runtime CLI/m);
  assert.match(cli(home, ['music-check'], { status: 1 }), /Unknown CLI command|Comando desconhecido/);
});
